### ISSUE TITLE
Play 2.3

### ISSUE THREAD

**Issue by miguelbaldi** [gigiigig/play-akka-angular-websocket#2]
Hi, first of all, thank you for this template!
This template made my WebSockets/Akka learning curve a lot smoother.
Recently I've took this template and upgraded to Play 2.3, and I would like to know if I can send you a pull request or if it's better to create another template. I've made minor changes to make use of new WebSockets API. What do you think?

Thanks

**Comment by gigiigig** [comment]
Hi Miguel, if you want to send a PR I'll be happy to merge it, I was thinking to update it anyway,
because it's becoming quite old now.

Thanks,
Luigi
